# Generated by Django 4.0.10 on 2023-03-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_is_active_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
